//! C FFI wrapper generation from LEZ IDL.
//!
//! Generates `extern "C"` functions that accept JSON strings and return JSON strings.
//! The generated FFI includes full transaction building via `wallet::WalletCore`.

use lez_framework_core::idl::*;
use std::fmt::Write;
use crate::util::*;

/// Generate C FFI wrapper source code from an IDL.
pub fn generate_ffi(idl: &LezIdl) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);
    let instr_enum = pascal_case(&idl.name) + "Instruction";

    // Header
    writeln!(out, "//! Auto-generated C FFI for the {} program.", idl.name).unwrap();
    writeln!(out, "//! Generated by lez-client-gen. DO NOT EDIT.").unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(out, "//! Required JSON fields for every instruction call:").unwrap();
    writeln!(out, "//!   - `wallet_path`: path to NSSA wallet directory").unwrap();
    writeln!(out, "//!   - `sequencer_url`: e.g. \"http://127.0.0.1:3040\"").unwrap();
    writeln!(out, "//!   - `program_id_hex`: 64-char hex string identifying the program").unwrap();
    writeln!(out).unwrap();

    // Imports
    writeln!(out, "use std::ffi::{{CStr, CString}};").unwrap();
    writeln!(out, "use std::os::raw::c_char;").unwrap();
    writeln!(out, "use serde::{{Serialize, Deserialize}};").unwrap();
    writeln!(out, "use serde_json::{{Value, json}};").unwrap();
    writeln!(out, "use sha2::{{Sha256, Digest}};").unwrap();
    writeln!(out, "use nssa::{{AccountId, ProgramId, PublicTransaction}};").unwrap();
    writeln!(out, "use nssa::public_transaction::{{Message, WitnessSet}};").unwrap();
    writeln!(out, "use wallet::WalletCore;").unwrap();
    writeln!(out).unwrap();

    // Instruction enum
    writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
    writeln!(out, "pub enum {instr_enum} {{").unwrap();
    for ix in &idl.instructions {
        let variant = pascal_case(&ix.name);
        if ix.args.is_empty() {
            writeln!(out, "    {variant},").unwrap();
        } else {
            writeln!(out, "    {variant} {{").unwrap();
            for arg in &ix.args {
                let name = rust_ident(&arg.name);
                let ty = idl_type_to_rust(&arg.type_);
                writeln!(out, "        {name}: {ty},").unwrap();
            }
            writeln!(out, "    }},").unwrap();
        }
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Helpers
    writeln!(out, "fn cstr_to_str<'a>(ptr: *const c_char) -> Result<&'a str, String> {{").unwrap();
    writeln!(out, "    if ptr.is_null() {{ return Err(\"null pointer\".into()); }}").unwrap();
    writeln!(out, "    unsafe {{ CStr::from_ptr(ptr) }}.to_str().map_err(|e| format!(\"invalid UTF-8: {{}}\", e))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn to_cstring(s: String) -> *mut c_char {{").unwrap();
    writeln!(out, "    CString::new(s).unwrap_or_else(|_|").unwrap();
    writeln!(out, "        CString::new(r#\"{{\"success\":false,\"error\":\"null byte\"}}\"#).unwrap()").unwrap();
    writeln!(out, "    ).into_raw()").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn error_json(msg: &str) -> *mut c_char {{").unwrap();
    writeln!(out, "    to_cstring(format!(r#\"{{\"success\":false,\"error\":{{}}}}\"#, serde_json::json!(msg)))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // PDA helper
    writeln!(out, "fn compute_pda(seeds: &[&[u8]]) -> AccountId {{").unwrap();
    writeln!(out, "    let mut hasher = Sha256::new();").unwrap();
    writeln!(out, "    for seed in seeds {{").unwrap();
    writeln!(out, "        let mut padded = [0u8; 32];").unwrap();
    writeln!(out, "        let len = seed.len().min(32);").unwrap();
    writeln!(out, "        padded[..len].copy_from_slice(&seed[..len]);").unwrap();
    writeln!(out, "        hasher.update(&padded);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let hash: [u8; 32] = hasher.finalize().into();").unwrap();
    writeln!(out, "    AccountId::from(hash)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_program_id_hex helper
    writeln!(out, "fn parse_program_id_hex(s: &str) -> Result<ProgramId, String> {{").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() != 64 {{ return Err(format!(\"program_id hex must be 64 chars, got {{}}\", s.len())); }}").unwrap();
    writeln!(out, "    let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "    let mut pid = [0u32; 8];").unwrap();
    writeln!(out, "    for (i, chunk) in bytes.chunks(4).enumerate() {{").unwrap();
    writeln!(out, "        pid[i] = u32::from_le_bytes(chunk.try_into().unwrap());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Ok(pid)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_account_id helper
    writeln!(out, "fn parse_account_id(s: &str) -> Result<AccountId, String> {{").unwrap();
    writeln!(out, "    if let Ok(id) = s.parse() {{ return Ok(id); }}").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() == 64 {{").unwrap();
    writeln!(out, "        let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "        let mut arr = [0u8; 32]; arr.copy_from_slice(&bytes);").unwrap();
    writeln!(out, "        return Ok(AccountId::from(arr));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Err(format!(\"invalid AccountId: {{}}\", s))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // init_wallet helper
    writeln!(out, "fn init_wallet(v: &Value) -> Result<WalletCore, String> {{").unwrap();
    writeln!(out, "    let wallet_path = v[\"wallet_path\"].as_str().ok_or(\"missing wallet_path\")?;").unwrap();
    writeln!(out, "    let sequencer_url = v[\"sequencer_url\"].as_str().ok_or(\"missing sequencer_url\")?;").unwrap();
    writeln!(out, "    std::env::set_var(\"NSSA_WALLET_HOME_DIR\", wallet_path);").unwrap();
    writeln!(out, "    WalletCore::new(sequencer_url).map_err(|e| format!(\"wallet init: {{}}\", e))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Per-instruction FFI functions
    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));
        let variant = pascal_case(&ix.name);

        // Collect signer account indices
        let signer_accounts: Vec<&IdlAccountItem> = ix.accounts.iter().filter(|a| a.signer).collect();

        writeln!(out, "/// FFI: {} instruction.", ix.name).unwrap();
        writeln!(out, "#[no_mangle]").unwrap();
        writeln!(out, "pub extern \"C\" fn {fn_name}(args_json: *const c_char) -> *mut c_char {{").unwrap();
        writeln!(out, "    let args = match cstr_to_str(args_json) {{").unwrap();
        writeln!(out, "        Ok(s) => s, Err(e) => return error_json(&e),").unwrap();
        writeln!(out, "    }};").unwrap();
        writeln!(out, "    match {fn_name}_impl(args) {{").unwrap();
        writeln!(out, "        Ok(r) => to_cstring(r), Err(e) => error_json(&e),").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "fn {fn_name}_impl(args: &str) -> Result<String, String> {{").unwrap();
        writeln!(out, "    let v: Value = serde_json::from_str(args).map_err(|e| format!(\"invalid JSON: {{}}\", e))?;").unwrap();
        writeln!(out, "    let program_id = parse_program_id_hex(v[\"program_id_hex\"].as_str().ok_or(\"missing program_id_hex\")?)?;").unwrap();
        writeln!(out, "    let wallet = init_wallet(&v)?;").unwrap();
        writeln!(out).unwrap();

        // Parse instruction args
        for arg in &ix.args {
            let name = rust_ident(&arg.name);
            let parse_expr = idl_type_to_json_parse(&arg.type_, &format!("v[\"{}\"]", arg.name));
            writeln!(out, "    let {name} = {parse_expr};").unwrap();
        }
        writeln!(out).unwrap();

        // Resolve accounts
        for acc in &ix.accounts {
            let name = rust_ident(&acc.name);
            if let Some(pda) = &acc.pda {
                writeln!(out, "    let {name} = compute_pda(&[").unwrap();
                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Const { value } => writeln!(out, "        b\"{value}\",").unwrap(),
                        IdlSeed::Account { path } => writeln!(out, "        {}.as_ref(),", rust_ident(path)).unwrap(),
                        IdlSeed::Arg { path } => writeln!(out, "        &{} as &[u8],", rust_ident(path)).unwrap(),
                    }
                }
                writeln!(out, "    ]);").unwrap();
            } else {
                writeln!(out, "    let {name} = parse_account_id(v[\"{}\"].as_str().ok_or(\"missing {}\")?)?;",
                    acc.name, acc.name).unwrap();
            }
        }

        writeln!(out).unwrap();

        // Build account_ids vec
        writeln!(out, "    let account_ids: Vec<AccountId> = vec![").unwrap();
        for acc in &ix.accounts {
            writeln!(out, "        {},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "    ];").unwrap();

        // Signer IDs
        writeln!(out, "    let signer_ids: Vec<AccountId> = vec![").unwrap();
        for acc in &signer_accounts {
            writeln!(out, "        {},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "    ];").unwrap();
        writeln!(out).unwrap();

        // Build instruction
        if ix.args.is_empty() {
            writeln!(out, "    let instruction = {instr_enum}::{variant};").unwrap();
        } else {
            writeln!(out, "    let instruction = {instr_enum}::{variant} {{").unwrap();
            for arg in &ix.args {
                let name = rust_ident(&arg.name);
                writeln!(out, "        {name},").unwrap();
            }
            writeln!(out, "    }};").unwrap();
        }
        writeln!(out).unwrap();

        // Transaction via tokio block_on
        writeln!(out, "    let rt = tokio::runtime::Runtime::new().map_err(|e| format!(\"tokio: {{}}\", e))?;").unwrap();
        writeln!(out, "    let tx_hash = rt.block_on(async {{").unwrap();
        writeln!(out, "        let nonces = wallet.get_accounts_nonces(signer_ids.clone()).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"nonces: {{}}\", e))?;").unwrap();
        writeln!(out, "        let mut signing_keys = Vec::new();").unwrap();
        writeln!(out, "        for sid in &signer_ids {{").unwrap();
        writeln!(out, "            let key = wallet.storage().user_data").unwrap();
        writeln!(out, "                .get_pub_account_signing_key(*sid)").unwrap();
        writeln!(out, "                .ok_or_else(|| format!(\"signing key not found for {{}}\", sid))?;").unwrap();
        writeln!(out, "            signing_keys.push(key);").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        let message = Message::try_new(program_id, account_ids, nonces, instruction)").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"message: {{:?}}\", e))?;").unwrap();
        writeln!(out, "        let witness_set = WitnessSet::for_message(&message, &signing_keys);").unwrap();
        writeln!(out, "        let tx = PublicTransaction::new(message, witness_set);").unwrap();
        writeln!(out, "        wallet.sequencer_client.send_tx_public(tx).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"submit: {{}}\", e))").unwrap();
        writeln!(out, "            .map(|r| r.tx_hash.to_string())").unwrap();
        writeln!(out, "    }})?;").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    Ok(json!({{\"success\": true, \"tx_hash\": tx_hash}}).to_string())").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // Free + version
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_free_string(s: *mut c_char) {{").unwrap();
    writeln!(out, "    if !s.is_null() {{ unsafe {{ drop(CString::from_raw(s)) }}; }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_version() -> *mut c_char {{").unwrap();
    writeln!(out, "    to_cstring(\"{}\".to_string())", idl.version).unwrap();
    writeln!(out, "}}").unwrap();

    Ok(out)
}

/// Generate a C header file from an IDL.
pub fn generate_header(idl: &LezIdl) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);
    let guard = format!("{}_FFI_H", prefix.to_uppercase());

    writeln!(out, "/* Auto-generated C header for {} FFI. DO NOT EDIT. */", idl.name).unwrap();
    writeln!(out, "#ifndef {guard}").unwrap();
    writeln!(out, "#define {guard}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "extern \"C\" {{").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();

    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));
        writeln!(out, "/* {} instruction */", ix.name).unwrap();
        writeln!(out, "char* {fn_name}(const char* args_json);").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "void {prefix}_free_string(char* s);").unwrap();
    writeln!(out, "char* {prefix}_version(void);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#endif /* {guard} */").unwrap();

    Ok(out)
}
