//! C FFI wrapper generation from LEZ IDL.
//!
//! Each generated FFI function:
//! 1. Accepts a JSON args string via C char pointer
//! 2. Parses wallet/sequencer connection args + instruction-specific args
//! 3. Instantiates the generated `{Program}Client` (from `codegen.rs` output)
//! 4. Drives the async client method via a blocking `tokio::Runtime`
//! 5. Returns `{"success":true,"tx_hash":"..."}` or `{"success":false,"error":"..."}`
//!
//! The emitted FFI file imports the client via `use super::client::*;` —
//! both modules sit in the same `src/` dir, wired by `mod client; mod ffi;` in lib.rs.

use lez_framework_core::idl::*;
use std::fmt::Write;
use crate::util::*;

/// Generate C FFI wrapper source code from an IDL.
///
/// The emitted code assumes the generated client module is available as
/// `super::client` (i.e. `mod client;` declared in lib.rs alongside `mod ffi;`).
pub fn generate_ffi(idl: &LezIdl) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);
    let program_pascal = pascal_case(&idl.name);

    // ── Header ──────────────────────────────────────────────────────────────
    writeln!(out, "//! Auto-generated C FFI for the {} program.", idl.name).unwrap();
    writeln!(out, "//! Generated by lez-client-gen. DO NOT EDIT.").unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(out, "//! Common JSON args (required by every instruction):").unwrap();
    writeln!(out, "//!   - `sequencer_url`: e.g. \"http://127.0.0.1:3040\"").unwrap();
    writeln!(out, "//!   - `wallet_path`:   path to NSSA wallet dir (optional env fallback)").unwrap();
    writeln!(out, "//!   - `program_id`:     64-char hex program id").unwrap();
    writeln!(out).unwrap();

    // ── Imports ─────────────────────────────────────────────────────────────
    writeln!(out, "use std::ffi::{{CStr, CString}};").unwrap();
    writeln!(out, "use std::os::raw::c_char;").unwrap();
    writeln!(out, "use serde_json::{{Value, json}};").unwrap();
    writeln!(out, "use wallet::WalletCore;").unwrap();
    writeln!(out, "use super::client::*;").unwrap();
    writeln!(out).unwrap();

    // ── CStr / string helpers ────────────────────────────────────────────────
    writeln!(out, "fn cstr_to_str<'a>(ptr: *const c_char) -> Result<&'a str, String> {{").unwrap();
    writeln!(out, "    if ptr.is_null() {{ return Err(\"null pointer\".into()); }}").unwrap();
    writeln!(out, "    unsafe {{ CStr::from_ptr(ptr) }}.to_str().map_err(|e| format!(\"invalid UTF-8: {{}}\", e))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "fn to_cstring(s: String) -> *mut c_char {{").unwrap();
    writeln!(out, "    CString::new(s).unwrap_or_else(|_|").unwrap();
    writeln!(out, "        CString::new(r#\"{{\"success\":false,\"error\":\"null byte\"}}\"#).unwrap()").unwrap();
    writeln!(out, "    ).into_raw()").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "fn error_json(msg: &str) -> *mut c_char {{").unwrap();
    out.push_str("    to_cstring(format!(r#\"{{\"success\":false,\"error\":{}}}\"#, serde_json::json!(msg)))\n");
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // ── Shared helpers ───────────────────────────────────────────────────────
    // parse_account_id: base58 first, then hex fallback (mirrors the hand-written FFI)
    writeln!(out, "fn parse_account_id(s: &str) -> Result<nssa::AccountId, String> {{").unwrap();
    writeln!(out, "    if let Ok(id) = s.parse() {{ return Ok(id); }}").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() == 64 {{").unwrap();
    writeln!(out, "        let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "        let mut arr = [0u8; 32];").unwrap();
    writeln!(out, "        arr.copy_from_slice(&bytes);").unwrap();
    writeln!(out, "        return Ok(nssa::AccountId::from(arr));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Err(format!(\"invalid AccountId '{{}}': expected base58 or 64-char hex\", s))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "fn load_wallet(wallet_path: Option<&str>) -> Result<WalletCore, String> {{").unwrap();
    writeln!(out, "    if let Some(path) = wallet_path {{").unwrap();
    writeln!(out, "        std::env::set_var(\"NSSA_WALLET_HOME_DIR\", path);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    WalletCore::from_env().map_err(|e| format!(\"failed to load wallet: {{}}\", e))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // ── Per-instruction FFI functions ────────────────────────────────────────
    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));
        let method_name = rust_ident(&ix.name);
        let accounts_struct = format!("{}Accounts", pascal_case(&ix.name));

        // extern "C" entry point ─────────────────────────────────────────────
        writeln!(out, "/// FFI: {} instruction.", ix.name).unwrap();
        writeln!(out, "#[no_mangle]").unwrap();
        writeln!(out, "pub extern \"C\" fn {fn_name}(args_json: *const c_char) -> *mut c_char {{").unwrap();
        writeln!(out, "    let args = match cstr_to_str(args_json) {{").unwrap();
        writeln!(out, "        Ok(s) => s,").unwrap();
        writeln!(out, "        Err(e) => return error_json(&e),").unwrap();
        writeln!(out, "    }};").unwrap();
        writeln!(out, "    match {fn_name}_impl(args) {{").unwrap();
        writeln!(out, "        Ok(result) => to_cstring(result),").unwrap();
        writeln!(out, "        Err(e) => error_json(&e),").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // _impl: parse JSON, call client, return JSON ────────────────────────
        writeln!(out, "fn {fn_name}_impl(args: &str) -> Result<String, String> {{").unwrap();
        writeln!(out, "    let v: Value = serde_json::from_str(args)").unwrap();
        writeln!(out, "        .map_err(|e| format!(\"invalid JSON: {{}}\", e))?;").unwrap();
        writeln!(out).unwrap();

        // Connection args (common to every instruction)
        writeln!(out, "    // Connection args").unwrap();
        writeln!(out, "    let sequencer_url = v[\"sequencer_url\"].as_str()").unwrap();
        writeln!(out, "        .ok_or(\"missing 'sequencer_url'\")?;").unwrap();
        writeln!(out, "    std::env::set_var(\"NSSA_SEQUENCER_URL\", sequencer_url);").unwrap();
        writeln!(out, "    let wallet_path = v[\"wallet_path\"].as_str();").unwrap();
        writeln!(out, "    let program_id_hex = v[\"program_id\"].as_str()").unwrap();
        writeln!(out, "        .ok_or(\"missing 'program_id'\")?;").unwrap();
        writeln!(out, "    let program_id = parse_program_id_hex(program_id_hex)?;").unwrap();
        writeln!(out).unwrap();

        // Instruction args
        if !ix.args.is_empty() {
            writeln!(out, "    // Instruction args").unwrap();
            for arg in &ix.args {
                let name = rust_ident(&arg.name);
                let parse_expr = idl_type_to_json_parse(&arg.type_, &format!("v[\"{}\"]", arg.name));
                writeln!(out, "    let {name} = {parse_expr};").unwrap();
            }
            writeln!(out).unwrap();
        }

        // Accounts
        writeln!(out, "    // Accounts").unwrap();
        for acc in &ix.accounts {
            let name = rust_ident(&acc.name);
            if let Some(pda) = &acc.pda {
                // Compute via the static PDA helper on the client struct
                let pda_method = format!("compute_{}_pda", snake_case(&acc.name));
                let mut call_args: Vec<String> = Vec::new();
                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Const { .. } => {}
                        IdlSeed::Account { path } => call_args.push(format!("&{}", rust_ident(path))),
                        IdlSeed::Arg { path } => call_args.push(format!("&{}", rust_ident(path))),
                    }
                }
                writeln!(out, "    let {name} = {}Client::{}({});",
                    program_pascal, pda_method, call_args.join(", ")).unwrap();
            } else if acc.rest {
                // Optional rest array — default to empty vec if key absent
                let inner = idl_type_to_json_parse(
                    &IdlType::Vec { vec: Box::new(IdlType::Primitive("AccountId".to_string())) },
                    &format!("v[\"{}\"]", acc.name),
                );
                writeln!(out,
                    "    let {name} = if v[\"{}\"].is_null() {{ vec![] }} else {{ {inner} }};",
                    acc.name).unwrap();
            } else {
                // Explicit account: parse AccountId from JSON string
                let parse_expr = idl_type_to_json_parse(
                    &IdlType::Primitive("AccountId".to_string()),
                    &format!("v[\"{}\"]", acc.name),
                );
                writeln!(out, "    let {name} = {parse_expr};").unwrap();
            }
        }
        writeln!(out).unwrap();

        // Build accounts struct
        writeln!(out, "    let accounts = {accounts_struct} {{").unwrap();
        for acc in &ix.accounts {
            writeln!(out, "        {},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "    }};").unwrap();
        writeln!(out).unwrap();

        // Load wallet → instantiate client → block on async call
        writeln!(out, "    let wallet = load_wallet(wallet_path)?;").unwrap();
        writeln!(out, "    let client = {}Client::new(&wallet, program_id);", program_pascal).unwrap();
        writeln!(out, "    let rt = tokio::runtime::Runtime::new()").unwrap();
        writeln!(out, "        .map_err(|e| format!(\"tokio runtime: {{}}\", e))?;").unwrap();
        write!(out, "    let tx_hash = rt.block_on(client.{method_name}(accounts").unwrap();
        for arg in &ix.args {
            write!(out, ", {}", rust_ident(&arg.name)).unwrap();
        }
        writeln!(out, "))?;").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    Ok(json!({{\"success\": true, \"tx_hash\": tx_hash}}).to_string())").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // ── Free string ─────────────────────────────────────────────────────────
    writeln!(out, "/// Free a string returned by any {prefix}_* function.").unwrap();
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_free_string(s: *mut c_char) {{").unwrap();
    writeln!(out, "    if !s.is_null() {{ unsafe {{ drop(CString::from_raw(s)) }}; }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // ── Version ─────────────────────────────────────────────────────────────
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_version() -> *mut c_char {{").unwrap();
    writeln!(out, "    to_cstring(\"{}\".to_string())", idl.version).unwrap();
    writeln!(out, "}}").unwrap();

    Ok(out)
}

/// Generate a C header file from an IDL.
pub fn generate_header(idl: &LezIdl) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);
    let guard = format!("{}_FFI_H", prefix.to_uppercase());

    writeln!(out, "/* Auto-generated C header for {} FFI. DO NOT EDIT. */", idl.name).unwrap();
    writeln!(out, "#ifndef {guard}").unwrap();
    writeln!(out, "#define {guard}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "extern \"C\" {{").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();

    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));
        writeln!(out, "/* {} instruction */", ix.name).unwrap();
        writeln!(out, "char* {fn_name}(const char* args_json);").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "void {prefix}_free_string(char* s);").unwrap();
    writeln!(out, "char* {prefix}_version(void);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#endif /* {guard} */").unwrap();

    Ok(out)
}
